version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: api-spring-boot-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api-spring-boot-dev
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api-spring-boot-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: api-spring-boot-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15434:80"
    networks:
      - api-spring-boot-net
    depends_on:
      - postgres

networks:
  api-spring-boot-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
